name: imagicalmine
version: 1.0.0
author: ImagicalCorp
api:
- 1.0.0
- 2.0.0
main: imagicalmine\Main
commands:
  login:
    description: Logs into an account.
    usage: "/login <password>"
    permission: imagicalauth.command.login
    aliases: [l]
  register:
    description: Registers an account.
    usage: "/register <email> <password>"
    permission: imagicalauth.command.register
    aliases: [r, reg]
permissions:
  imagicalauth.command.login:
    default: op
  imagicalauth.command.register:
    default: op
